version: '2.1'
orbs:
  node: circleci/node@4.7.0
jobs:
  test:
    executor:
      name: node/default
      tag: '14.17.1'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test --maxWorkers=4
          name: Run YARN tests

workflows:
  test_browser_extension_with_yarn:
    jobs:
      - test
