orbs:
  node: circleci/node@4.3.0

version: 2.1

workflows:
  matrix-tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              pkg-manager: yarn
              version:
                - 12.22.1
                - 14.16.1
                - 16.0.0
